/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MetadataValue = IDL.Rec();
export const TokenId = IDL.Nat;
export const Timestamp = IDL.Int;
export const NFTInfo = IDL.Record({
  'id' : TokenId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'mintedAt' : Timestamp,
});
export const Account = IDL.Record({
  'owner' : IDL.Principal,
  'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
MetadataValue.fill(
  IDL.Variant({
    'Int' : IDL.Int,
    'Map' : IDL.Vec(IDL.Tuple(IDL.Text, MetadataValue)),
    'Nat' : IDL.Nat,
    'Blob' : IDL.Vec(IDL.Nat8),
    'Text' : IDL.Text,
    'Array' : IDL.Vec(MetadataValue),
  })
);
export const MintResult = IDL.Variant({ 'ok' : TokenId, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getNFTsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(NFTInfo)], ['query']),
  'getTokenImage' : IDL.Func(
      [TokenId],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'icrc7_balance_of' : IDL.Func(
      [IDL.Vec(Account)],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'icrc7_collection_metadata' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, MetadataValue))],
      ['query'],
    ),
  'icrc7_default_take_value' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'icrc7_max_query_batch_size' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'icrc7_max_take_value' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'icrc7_max_update_batch_size' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'icrc7_name' : IDL.Func([], [IDL.Text], ['query']),
  'icrc7_owner_of' : IDL.Func(
      [IDL.Vec(TokenId)],
      [IDL.Vec(IDL.Opt(Account))],
      ['query'],
    ),
  'icrc7_symbol' : IDL.Func([], [IDL.Text], ['query']),
  'icrc7_token_metadata' : IDL.Func(
      [IDL.Vec(TokenId)],
      [IDL.Vec(IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, MetadataValue))))],
      ['query'],
    ),
  'icrc7_tokens' : IDL.Func(
      [IDL.Opt(TokenId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(TokenId)],
      ['query'],
    ),
  'icrc7_tokens_of' : IDL.Func(
      [Account, IDL.Opt(TokenId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(TokenId)],
      ['query'],
    ),
  'icrc7_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
  'mint' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)], [MintResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MetadataValue = IDL.Rec();
  const TokenId = IDL.Nat;
  const Timestamp = IDL.Int;
  const NFTInfo = IDL.Record({
    'id' : TokenId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'mintedAt' : Timestamp,
  });
  const Account = IDL.Record({
    'owner' : IDL.Principal,
    'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  MetadataValue.fill(
    IDL.Variant({
      'Int' : IDL.Int,
      'Map' : IDL.Vec(IDL.Tuple(IDL.Text, MetadataValue)),
      'Nat' : IDL.Nat,
      'Blob' : IDL.Vec(IDL.Nat8),
      'Text' : IDL.Text,
      'Array' : IDL.Vec(MetadataValue),
    })
  );
  const MintResult = IDL.Variant({ 'ok' : TokenId, 'err' : IDL.Text });
  
  return IDL.Service({
    'getNFTsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(NFTInfo)], ['query']),
    'getTokenImage' : IDL.Func(
        [TokenId],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'icrc7_balance_of' : IDL.Func(
        [IDL.Vec(Account)],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'icrc7_collection_metadata' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, MetadataValue))],
        ['query'],
      ),
    'icrc7_default_take_value' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'icrc7_max_query_batch_size' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'icrc7_max_take_value' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'icrc7_max_update_batch_size' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'icrc7_name' : IDL.Func([], [IDL.Text], ['query']),
    'icrc7_owner_of' : IDL.Func(
        [IDL.Vec(TokenId)],
        [IDL.Vec(IDL.Opt(Account))],
        ['query'],
      ),
    'icrc7_symbol' : IDL.Func([], [IDL.Text], ['query']),
    'icrc7_token_metadata' : IDL.Func(
        [IDL.Vec(TokenId)],
        [IDL.Vec(IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, MetadataValue))))],
        ['query'],
      ),
    'icrc7_tokens' : IDL.Func(
        [IDL.Opt(TokenId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(TokenId)],
        ['query'],
      ),
    'icrc7_tokens_of' : IDL.Func(
        [Account, IDL.Opt(TokenId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(TokenId)],
        ['query'],
      ),
    'icrc7_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
    'mint' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [MintResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };