/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'owner' : Principal,
  'subaccount' : [] | [Uint8Array],
}
export type MetadataValue = { 'Int' : bigint } |
  { 'Map' : Array<[string, MetadataValue]> } |
  { 'Nat' : bigint } |
  { 'Blob' : Uint8Array } |
  { 'Text' : string } |
  { 'Array' : Array<MetadataValue> };
export type MintResult = { 'ok' : TokenId } |
  { 'err' : string };
export interface NFTInfo {
  'id' : TokenId,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'mintedAt' : Timestamp,
}
export type Timestamp = bigint;
export type TokenId = bigint;
export interface _SERVICE {
  'getNFTsByOwner' : ActorMethod<[Principal], Array<NFTInfo>>,
  'getTokenImage' : ActorMethod<[TokenId], [] | [Uint8Array]>,
  'icrc7_balance_of' : ActorMethod<[Array<Account>], Array<bigint>>,
  'icrc7_collection_metadata' : ActorMethod<[], Array<[string, MetadataValue]>>,
  'icrc7_default_take_value' : ActorMethod<[], [] | [bigint]>,
  'icrc7_max_query_batch_size' : ActorMethod<[], [] | [bigint]>,
  'icrc7_max_take_value' : ActorMethod<[], [] | [bigint]>,
  'icrc7_max_update_batch_size' : ActorMethod<[], [] | [bigint]>,
  'icrc7_name' : ActorMethod<[], string>,
  'icrc7_owner_of' : ActorMethod<[Array<TokenId>], Array<[] | [Account]>>,
  'icrc7_symbol' : ActorMethod<[], string>,
  'icrc7_token_metadata' : ActorMethod<
    [Array<TokenId>],
    Array<[] | [Array<[string, MetadataValue]>]>
  >,
  'icrc7_tokens' : ActorMethod<[[] | [TokenId], [] | [bigint]], Array<TokenId>>,
  'icrc7_tokens_of' : ActorMethod<
    [Account, [] | [TokenId], [] | [bigint]],
    Array<TokenId>
  >,
  'icrc7_total_supply' : ActorMethod<[], bigint>,
  'mint' : ActorMethod<[string, string, Uint8Array], MintResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];