/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type MetadataValue = {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, MetadataValue]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<MetadataValue>;
};
export type MintResult = {
    __kind__: "ok";
    ok: TokenId;
} | {
    __kind__: "err";
    err: string;
};
export type Timestamp = bigint;
export interface Account {
    owner: Principal;
    subaccount?: Uint8Array;
}
export type TokenId = bigint;
export interface NFTInfo {
    id: TokenId;
    owner: Principal;
    name: string;
    description: string;
    mintedAt: Timestamp;
}
export interface backendInterface {
    getNFTsByOwner(owner: Principal): Promise<Array<NFTInfo>>;
    getTokenImage(tokenId: TokenId): Promise<Uint8Array | null>;
    icrc7_balance_of(accounts: Array<Account>): Promise<Array<bigint>>;
    icrc7_collection_metadata(): Promise<Array<[string, MetadataValue]>>;
    icrc7_default_take_value(): Promise<bigint | null>;
    icrc7_max_query_batch_size(): Promise<bigint | null>;
    icrc7_max_take_value(): Promise<bigint | null>;
    icrc7_max_update_batch_size(): Promise<bigint | null>;
    icrc7_name(): Promise<string>;
    icrc7_owner_of(token_ids: Array<TokenId>): Promise<Array<Account | null>>;
    icrc7_symbol(): Promise<string>;
    icrc7_token_metadata(token_ids: Array<TokenId>): Promise<Array<Array<[string, MetadataValue]> | null>>;
    icrc7_tokens(prev: TokenId | null, take: bigint | null): Promise<Array<TokenId>>;
    icrc7_tokens_of(account: Account, prev: TokenId | null, take: bigint | null): Promise<Array<TokenId>>;
    icrc7_total_supply(): Promise<bigint>;
    mint(name: string, description: string, image: Uint8Array): Promise<MintResult>;
}
import type { Account as _Account, MetadataValue as _MetadataValue, MintResult as _MintResult, TokenId as _TokenId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getNFTsByOwner(arg0: Principal): Promise<Array<NFTInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNFTsByOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNFTsByOwner(arg0);
            return result;
        }
    }
    async getTokenImage(arg0: TokenId): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenImage(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenImage(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_balance_of(arg0: Array<Account>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_balance_of(to_candid_vec_n2(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_balance_of(to_candid_vec_n2(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async icrc7_collection_metadata(): Promise<Array<[string, MetadataValue]>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_collection_metadata();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_collection_metadata();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_default_take_value(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_default_take_value();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_default_take_value();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_max_query_batch_size(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_max_query_batch_size();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_max_query_batch_size();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_max_take_value(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_max_take_value();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_max_take_value();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_max_update_batch_size(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_max_update_batch_size();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_max_update_batch_size();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_name(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_name();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_name();
            return result;
        }
    }
    async icrc7_owner_of(arg0: Array<TokenId>): Promise<Array<Account | null>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_owner_of(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_owner_of(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_symbol(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_symbol();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_symbol();
            return result;
        }
    }
    async icrc7_token_metadata(arg0: Array<TokenId>): Promise<Array<Array<[string, MetadataValue]> | null>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_token_metadata(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_token_metadata(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_tokens(arg0: TokenId | null, arg1: bigint | null): Promise<Array<TokenId>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_tokens(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_tokens(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async icrc7_tokens_of(arg0: Account, arg1: TokenId | null, arg2: bigint | null): Promise<Array<TokenId>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_tokens_of(to_candid_Account_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_tokens_of(to_candid_Account_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async icrc7_total_supply(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_total_supply();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_total_supply();
            return result;
        }
    }
    async mint(arg0: string, arg1: string, arg2: Uint8Array): Promise<MintResult> {
        if (this.processError) {
            try {
                const result = await this.actor.mint(arg0, arg1, arg2);
                return from_candid_MintResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mint(arg0, arg1, arg2);
            return from_candid_MintResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Account_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Account): Account {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MetadataValue_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetadataValue): MetadataValue {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MintResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MintResult): MintResult {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : from_candid_Account_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<[string, _MetadataValue]>]): Array<[string, MetadataValue]> | null {
    return value.length === 0 ? null : from_candid_vec_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    subaccount: [] | [Uint8Array];
}): {
    owner: Principal;
    subaccount?: Uint8Array;
} {
    return {
        owner: value.owner,
        subaccount: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.subaccount))
    };
}
function from_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _MetadataValue]): [string, MetadataValue] {
    return [
        value[0],
        from_candid_MetadataValue_n7(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TokenId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TokenId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Int: bigint;
} | {
    Map: Array<[string, _MetadataValue]>;
} | {
    Nat: bigint;
} | {
    Blob: Uint8Array;
} | {
    Text: string;
} | {
    Array: Array<_MetadataValue>;
}): {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, MetadataValue]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<MetadataValue>;
} {
    return "Int" in value ? {
        __kind__: "Int",
        Int: value.Int
    } : "Map" in value ? {
        __kind__: "Map",
        Map: from_candid_vec_n5(_uploadFile, _downloadFile, value.Map)
    } : "Nat" in value ? {
        __kind__: "Nat",
        Nat: value.Nat
    } : "Blob" in value ? {
        __kind__: "Blob",
        Blob: value.Blob
    } : "Text" in value ? {
        __kind__: "Text",
        Text: value.Text
    } : "Array" in value ? {
        __kind__: "Array",
        Array: from_candid_vec_n9(_uploadFile, _downloadFile, value.Array)
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [_Account]>): Array<Account | null> {
    return value.map((x)=>from_candid_opt_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [Array<[string, _MetadataValue]>]>): Array<Array<[string, MetadataValue]> | null> {
    return value.map((x)=>from_candid_opt_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _MetadataValue]>): Array<[string, MetadataValue]> {
    return value.map((x)=>from_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MetadataValue>): Array<MetadataValue> {
    return value.map((x)=>from_candid_MetadataValue_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Account_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Account): _Account {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenId | null): [] | [_TokenId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    subaccount?: Uint8Array;
}): {
    owner: Principal;
    subaccount: [] | [Uint8Array];
} {
    return {
        owner: value.owner,
        subaccount: value.subaccount ? candid_some(value.subaccount) : candid_none()
    };
}
function to_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Account>): Array<_Account> {
    return value.map((x)=>to_candid_Account_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
